name: craftz_app
description: Craftz Administration App.
version: 1.3.6

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  http: ^1.0.0
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1
  flutter_native_splash: ^2.4.4
  shared_preferences: ^2.4.0
  flutter_dotenv: ^5.0.2
  flutter_slidable: ^4.0.0
  intl: ^0.18.1
  package_info_plus: ^8.3.0
  file_saver: ^0.2.14
  open_filex: ^4.7.0
  html_to_pdf: ^0.8.1
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - .env
    - assets/splashScreen/
  uses-material-design: true
  fonts:
    - family: Eras
      fonts:
        - asset: assets/fonts/ITC Eras Light Regular.otf
          weight: 200
        - asset: assets/fonts/ITC Eras Book Regular.otf
          weight: 300
        - asset: assets/fonts/ITC Eras Medium.otf
          weight: 500
        - asset: assets/fonts/ITC Eras Demi Regular.otf
          weight: 700
        - asset: assets/fonts/ITC Eras Bold.otf
          weight: 800
        - asset: assets/fonts/ITC Eras Ultra Regular.otf
          weight: 900

flutter_launcher_icons:
  android: "launcher_icon"
  image_path_android: assets/icon/icon.jpg
  adaptive_icon_foreground: "assets/icon/front.png" # Ruta del ícono de primer plano
  adaptive_icon_background: "assets/icon/back.png"
  min_sdk_android: 21

flutter_native_splash:
  android: true
  ios: true
  web: false

  color: "#292662"
  image: "assets/splashScreen/old_logo.png"
  branding: "assets/splashScreen/old_branding.png"

  android_12:
    color: "#292662"
    image: "assets/splashScreen/logo.png"
    branding: "assets/splashScreen/branding.png"